services:
    register_walk_in_handler:
        class: Derp\Application\RegisterWalkInHandler
        arguments:
            - @patient_repository
        tags:
            - { name: command_handler, handles: Derp\Application\RegisterWalkIn }

    doctrine_patient_repository:
        class: Derp\Infrastructure\Persistence\DoctrinePatientRepository
        arguments:
            - @doctrine

    patient_repository:
        alias: doctrine_patient_repository

    patient_list_view_model_repository:
        class: Derp\Infrastructure\View\PatientListViewModelRepository
        arguments:
            - @patient_repository

    when_walk_in_registered_send_notification_email:
        class: Derp\Infrastructure\Notification\WhenWalkInRegisteredSendNotificationEmail
        arguments:
            - @mailer
            - @logger
        tags:
            - { name: asynchronous_event_subscriber, subscribes_to: Derp\Domain\Model\Patient\WalkInRegistered }

# TODO move this to /Derp/Infrastructure/Cli/Resources/config/services
    register_walk_in_console_command:
        class: Derp\Infrastructure\Cli\RegisterWalkInCommand
        tags:
            - { name: console.command }

# TODO move this to /Derp/Infrastructure/Web/Resources/config/services
    patient_controller:
        class: Derp\Infrastructure\Web\Controller\PatientController
        calls:
            - [setContainer, [@service_container]]

# TODO move this to /Derp/Infrastructure/Api/Resources/config/services.yml
    rest_patient_controller:
        class: Derp\Infrastructure\Api\Controller\RestPatientController
        calls:
            - [setContainer, [@service_container]]
