old_sound_rabbit_mq:
    enable_collector: true
    connections:
        default:
            host:     'localhost'
            port:     5672
            user:     'user'
            password: 'password'
            vhost:    '/'
    producers:
        asynchronous_events:
            connection:       default
            exchange_options: { name: 'asynchronous_events', type: direct }
        asynchronous_commands:
            connection:       default
            exchange_options: { name: 'asynchronous_commands', type: direct }
    consumers:
        asynchronous_events:
            connection:       default
            exchange_options: { name: 'asynchronous_events', type: direct }
            queue_options:    { name: 'asynchronous_events' }
            callback:         simple_bus.rabbit_mq_bundle_bridge.events_consumer
        asynchronous_commands:
            connection:       default
            exchange_options: { name: 'asynchronous_commands', type: direct }
            queue_options:    { name: 'asynchronous_commands' }
            callback:         simple_bus.rabbit_mq_bundle_bridge.commands_consumer

simple_bus_rabbit_mq_bundle_bridge:
    commands:
        producer_service_id: old_sound_rabbit_mq.asynchronous_commands_producer
    events:
        producer_service_id: old_sound_rabbit_mq.asynchronous_events_producer

simple_bus_asynchronous:
    commands:
        logging: ~
    events:
        logging: ~
