services:
    register_walk_in_handler:
        class: Derp\Application\RegisterWalkInHandler
        arguments:
            - @patient_repository
        tags:
            - { name: command_handler, handles: Derp\Application\RegisterWalkIn }

    doctrine_patient_repository:
        class: Derp\Infrastructure\Persistence\DoctrinePatientRepository
        arguments:
            - @doctrine

    patient_repository:
        alias: doctrine_patient_repository

    patient_list_view_model_repository:
        class: Derp\Infrastructure\View\PatientListViewModelRepository
        arguments:
            - @patient_repository

    when_walk_in_registered_send_notification_email:
        class: Derp\Infrastructure\Notification\WhenWalkInRegisteredSendNotificationEmail
        arguments:
            - @mailer
        tags:
            - { name: event_subscriber, subscribes_to: Derp\Bundle\ERBundle\Entity\WalkInRegistered }
