---
server:
    install: '1'
    timezone: Europe/Amsterdam
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: default, ip: 192.168.33.99, memory: '512', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
nginx:
    install: '1'
    docroot: /vagrant/web/
    servername: myApp.vb
mysql:
    install: '1'
    root_password: password
    database: hexagonal_architecture
    user: user
    password: password
    dump: ''
rabbitmq:
    install: '1'
    user: user
    password: password
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-mysql]
xdebug:
    install: '1'
composer:
    install: '1'

